---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - phpipam_on_azure-vars.yml
  roles:
  - azure-resourcegroup
  - azure-vm
  - azure-mysql

  tasks:
  - name: Add VM IP address to the inventory
    add_host:
      hostname: "{{ output_ip_address.state.ip_address }}"
      groups: "new-azurevm"
      ansible_user: azureuser
      ansible_become: true
  - set_fact: vm_ip="{{ output_ip_address.state.ip_address }}"
  - name: Notification
    debug:
      msg: "Accessing new Azure VM to start installing phpIPAM."

- hosts: "new-azurevm"
  vars_files:
    - phpipam_on_azure-vars.yml
  roles:
  - webserver-apachephp
  - phpipam

  tasks:
  - name: Service available message
    debug:
      msg: "phpIPAM is available on http://{{ hostvars['localhost']['vm_ip'] }} with username 'admin' and password 'ipamadmin'."