---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - phpipam-vars.yml
  roles:
  - azure-resourcegroup
  - azure-vm
  - azure-mysql

  tasks:
  - add_host:
      hostname: "{{ output_ip_address.state.ip_address }}"
      groups: "new-azurevm"
      ansible_user: azureuser
      ansible_become: true

- hosts: "new-azurevm"
  sudo: yes
  vars_files:
    - phpipam-vars.yml
  roles:
  - webserver-apachephp
  - phpipam