---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - add_host:
      hostname: novohostname
      groups: novogrupo

- hosts: novogrupo
  connection: local
  gather_facts: False
  tasks:
  - debug:
    msg: "The public IP"