---
- name: Clone phpipam files from Git
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: /var/www/phpipam
- name: Copy database config file
  shell: |
    sudo cp /var/www/phpipam/config.dist.php /var/www/phpipam/config.php
    exit 0
- name: Edit db config file - DB host
  replace:
    path: /var/www/phpipam/config.php
    regexp: "host'] = 'localhost';"
    replace: "host'] = '{{ mysqlserver_name }}.mysql.database.azure.com';"
- name: Edit db config file - DB Username
  replace:
    path: /var/www/phpipam/config.php
    regexp: "user'] = 'phpipam';"
    replace: "user'] = '{{ admin_username }}@{{ mysqlserver_name }}';"
- name: Edit db config file - Password
  replace:
    path: /var/www/phpipam/config.php
    regexp: "pass'] = 'phpipamadmin';"
    replace: "pass'] = '{{ admin_password }}';"
- name: Edit db config file - DB name
  replace:
    path: /var/www/phpipam/config.php
    regexp: "name'] = 'phpipam';="
    replace: "name'] = '{{ mysqldb_name }}';"
- name: Change apache website root folder
  replace:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: "DocumentRoot /var/www/html"
    replace: "DocumentRoot /var/www/phpipam"
- name: Deploy database
  shell: |
    mysql -u "{{ admin_username }}@{{ mysqlserver_name }}" -h "{{ mysqlserver_name }}.mysql.database.azure.com" -p "{{ admin_password }}" phpipam < /var/www/phpipam/db/SCHEMA.sql
    exit 0
- name: Restart apache
  shell: |
    sudo systemctl restart apache2
    exit 0