- name: Update Repository cache
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - squid
