---
- name: Install Apache
  apt: name=apache2 state=latest
- name: Install PHP
  apt: name=php state=latest
- name: Install libapache2-mod-php
  apt: name=libapache2-mod-php state=latest
- name: Install php-mysql
  apt: name=php-mysql state=latest
- name: Install php-gmp
  apt: name=php-gmp state=latest
- name: Install php-mbstring
  apt: name=php-mbstring state=latest
- name: Install php-gd
  apt: name=php-gd state=latest
- name: Install php-pear
  apt: name=php-pear state=latest
- name: Install mysql-client
  apt: name=mysql-client-core-5.7 state=latest
- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present
- name: Restart apache
  shell: "sudo systemctl restart apache2"