---
- name: Install Apache/PHP server and MySQL client
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - apache2
    - php
    - libapache2
    - php-mysql
    - php-gmp
    - php-mbstring
    - php-gd
    - php-pear
    - mysql-client-core-5.7
- name: Enabled mod_rewrite
  apache2_module: name=rewrite state=present
- name: Restart apache
  shell: "sudo systemctl restart apache2"